version: "3"

services:
    postgres:
        image: "docker.io/postgres:13"
        restart: unless-stopped
        expose:
            - "5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
        env_file:
            - docker/database.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kachna"]
            interval: 5s
            timeout: 5s
            retries: 5
    api:
        build:
            context: ./KachnaOnline.App
            dockerfile: Dockerfile.development
        restart: unless-stopped
        volumes:
            - ./:/src:z
        env_file:
            - docker/api.env
        environment:
            # Override the default URLs to expose the API outside the container
            - URLS=https://+:5001;http://+:5000
        ports:
            - "5000:5000"
            - "5001:5001"
        depends_on:
            postgres:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl -k https://localhost:5001/kachna/api/states/current"]
            interval: 5s
            timeout: 5s
            retries: 5
        command: "${DOTNET_ARGS:-}"
    frontend:
        build:
            context: ./ClientApp/KachnaOnline
        restart: unless-stopped
        volumes:
            - ./ClientApp/KachnaOnline/:/src:z
        ports:
            - "4200:4200"
        depends_on:
            api:
                condition: service_healthy

volumes:
    database-data:
